/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as casino from "./casino";
export type { casino };
import type * as games from "./games";
export type { games };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { GameMaster } from "./GameMaster";
export type { Points } from "./Points";
