/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoints,
  IPointsInterface,
} from "../../../../../contracts/hackathon/morse/MorseProxy.sol/IPoints";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "ad7b985e",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPoints__factory {
  static readonly abi = _abi;
  static createInterface(): IPointsInterface {
    return new Interface(_abi) as IPointsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPoints {
    return new Contract(address, _abi, runner) as unknown as IPoints;
  }
}
