/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  PointsReceiver,
  PointsReceiverInterface,
} from "../../../../../contracts/hackathon/morse/MorseProxy.sol/PointsReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "address",
        name: "_challenge",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "callZ5",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "challenge",
    outputs: [
      {
        internalType: "contract IMorse",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "forward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x60c03461009757601f61032538819003918201601f19168301916001600160401b0383118484101761009c57808492604094855283398101031261009757610052602061004b836100b2565b92016100b2565b6080919091526001600160a01b031660a05260405161025e90816100c7823960805181818160a70152818160ee0152610134015260a051818181605e01526101650152f35b600080fd5b634e487b7160e01b600052604160045260246000fd5b51906001600160a01b03821682036100975756fe6080604052600436101561001257600080fd5b6000803560e01c80636096395d1461011d5780638da5cb5b146100d8578063d264e05e146100905763d2ef73981461004957600080fd5b3461008d578060031936011261008d576040517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b80fd5b503461008d578060031936011261008d576100d5337f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316146101f0565b80f35b503461008d578060031936011261008d576040517f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03168152602090f35b503461008d578060031936011261008d57610162337f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316146101f0565b807f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316803b156101ed57819060046040518094819363088fa68560e11b83525af180156101e2576101b9575080f35b67ffffffffffffffff81116101ce5760405280f35b634e487b7160e01b82526041600452602482fd5b6040513d84823e3d90fd5b50fd5b156101f757565b60405162461bcd60e51b81526020600482015260096024820152683737ba1037bbb732b960b91b6044820152606490fdfea2646970667358221220fea07a28ccf4febb8b8509613748a255b4ca455f754926eaf6d926b80a5709e164736f6c634300081c0033";

type PointsReceiverConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PointsReceiverConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PointsReceiver__factory extends ContractFactory {
  constructor(...args: PointsReceiverConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    _owner: AddressLike,
    _challenge: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(_owner, _challenge, overrides || {});
  }
  override deploy(
    _owner: AddressLike,
    _challenge: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(_owner, _challenge, overrides || {}) as Promise<
      PointsReceiver & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PointsReceiver__factory {
    return super.connect(runner) as PointsReceiver__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PointsReceiverInterface {
    return new Interface(_abi) as PointsReceiverInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): PointsReceiver {
    return new Contract(address, _abi, runner) as unknown as PointsReceiver;
  }
}
