/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as biddingSol from "./Bidding.sol";
export type { biddingSol };
import type * as descendSol from "./Descend.sol";
export type { descendSol };
import type * as doorsSol from "./Doors.sol";
export type { doorsSol };
import type * as equilibriumSol from "./Equilibrium.sol";
export type { equilibriumSol };
import type * as threesSol from "./Threes.sol";
export type { threesSol };
