/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Descend__factory } from "./Descend__factory";
export { IRagnarokGameMaster__factory } from "./IRagnarokGameMaster__factory";
