/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRagnarokGameMaster,
  IRagnarokGameMasterInterface,
} from "../../../../contracts/games/Descend.sol/IRagnarokGameMaster";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "player",
        type: "address",
      },
    ],
    name: "playerEliminated",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IRagnarokGameMaster__factory {
  static readonly abi = _abi;
  static createInterface(): IRagnarokGameMasterInterface {
    return new Interface(_abi) as IRagnarokGameMasterInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IRagnarokGameMaster {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IRagnarokGameMaster;
  }
}
