/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPoints,
  IPointsInterface,
} from "../../../../contracts/casino/climb.sol/IPoints";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "pointsAmount",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "isWithdrawable",
        type: "bool",
      },
    ],
    name: "awardPointsForPayout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
    ],
    name: "depositFor",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IPoints__factory {
  static readonly abi = _abi;
  static createInterface(): IPointsInterface {
    return new Interface(_abi) as IPointsInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IPoints {
    return new Contract(address, _abi, runner) as unknown as IPoints;
  }
}
