/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Authorizer } from "./Authorizer";
export type { IMorse } from "./IMorse";
export type { IPoints } from "./IPoints";
export type { MorseReceiver } from "./MorseReceiver";
