/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ChallengeHard1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "FLOOR_LIMIT"
      | "balanceOf"
      | "calculateAvailableLiquidity"
      | "egressLiquidity"
      | "ingressLiquidity"
      | "vaultLib"
      | "verifySystemCompletion"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "FLOOR_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateAvailableLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "egressLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ingressLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "vaultLib", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifySystemCompletion",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "FLOOR_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateAvailableLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "egressLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ingressLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultLib", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifySystemCompletion",
    data: BytesLike
  ): Result;
}

export interface ChallengeHard1 extends BaseContract {
  connect(runner?: ContractRunner | null): ChallengeHard1;
  waitForDeployment(): Promise<this>;

  interface: ChallengeHard1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FLOOR_LIMIT: TypedContractMethod<[], [bigint], "view">;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  calculateAvailableLiquidity: TypedContractMethod<
    [assetValue: BigNumberish],
    [bigint],
    "view"
  >;

  egressLiquidity: TypedContractMethod<
    [liquidityAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  ingressLiquidity: TypedContractMethod<[], [void], "payable">;

  vaultLib: TypedContractMethod<[], [string], "view">;

  verifySystemCompletion: TypedContractMethod<[], [string], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FLOOR_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateAvailableLiquidity"
  ): TypedContractMethod<[assetValue: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "egressLiquidity"
  ): TypedContractMethod<[liquidityAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ingressLiquidity"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "vaultLib"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifySystemCompletion"
  ): TypedContractMethod<[], [string], "nonpayable">;

  filters: {};
}
