/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IVaultLibInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calcAssetAllocation"
      | "calcAssetForWithdrawals"
      | "verify"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calcAssetAllocation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calcAssetForWithdrawals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "verify", values: [AddressLike]): string;

  decodeFunctionResult(
    functionFragment: "calcAssetAllocation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcAssetForWithdrawals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;
}

export interface IVaultLib extends BaseContract {
  connect(runner?: ContractRunner | null): IVaultLib;
  waitForDeployment(): Promise<this>;

  interface: IVaultLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calcAssetAllocation: TypedContractMethod<
    [value: BigNumberish],
    [bigint],
    "view"
  >;

  calcAssetForWithdrawals: TypedContractMethod<
    [value: BigNumberish],
    [bigint],
    "view"
  >;

  verify: TypedContractMethod<[user: AddressLike], [void], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calcAssetAllocation"
  ): TypedContractMethod<[value: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calcAssetForWithdrawals"
  ): TypedContractMethod<[value: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "verify"
  ): TypedContractMethod<[user: AddressLike], [void], "view">;

  filters: {};
}
