/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IRagnarok,
  IRagnarokInterface,
} from "../../../contracts/GameMaster.sol/IRagnarok";

const _abi = [
  {
    inputs: [],
    name: "getRegisteredPlayers",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IRagnarok__factory {
  static readonly abi = _abi;
  static createInterface(): IRagnarokInterface {
    return new Interface(_abi) as IRagnarokInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IRagnarok {
    return new Contract(address, _abi, runner) as unknown as IRagnarok;
  }
}
