/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Caller } from "./Caller";
export type { IMorse } from "./IMorse";
export type { IPoints } from "./IPoints";
export type { MorseProxy } from "./MorseProxy";
export type { PointsForwarder } from "./PointsForwarder";
