/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface MorseProxyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "caller"
      | "challenge"
      | "forwardPoints"
      | "forwarder"
      | "makeItLookLikeCode"
      | "proxyZ1"
      | "proxyZ5"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "caller", values?: undefined): string;
  encodeFunctionData(functionFragment: "challenge", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "forwardPoints",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "forwarder", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "makeItLookLikeCode",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "proxyZ1", values?: undefined): string;
  encodeFunctionData(functionFragment: "proxyZ5", values?: undefined): string;

  decodeFunctionResult(functionFragment: "caller", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "challenge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forwardPoints",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "forwarder", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "makeItLookLikeCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proxyZ1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "proxyZ5", data: BytesLike): Result;
}

export interface MorseProxy extends BaseContract {
  connect(runner?: ContractRunner | null): MorseProxy;
  waitForDeployment(): Promise<this>;

  interface: MorseProxyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  caller: TypedContractMethod<[], [string], "view">;

  challenge: TypedContractMethod<[], [string], "view">;

  forwardPoints: TypedContractMethod<[], [void], "nonpayable">;

  forwarder: TypedContractMethod<[], [string], "view">;

  makeItLookLikeCode: TypedContractMethod<[], [void], "nonpayable">;

  proxyZ1: TypedContractMethod<[], [void], "nonpayable">;

  proxyZ5: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "caller"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "challenge"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "forwardPoints"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "forwarder"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "makeItLookLikeCode"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proxyZ1"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proxyZ5"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
