/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMorse } from "./IMorse";
export type { MorseCaller } from "./MorseCaller";
export type { MorseFactory } from "./MorseFactory";
