/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as finalExploitSol from "./FinalExploit.sol";
export type { finalExploitSol };
import type * as minimalSol from "./Minimal.sol";
export type { minimalSol };
import type * as morseDestructSol from "./MorseDestruct.sol";
export type { morseDestructSol };
import type * as morseExploitSol from "./MorseExploit.sol";
export type { morseExploitSol };
import type * as morseFactorySol from "./MorseFactory.sol";
export type { morseFactorySol };
import type * as morseProxySol from "./MorseProxy.sol";
export type { morseProxySol };
import type * as morseReceiverSol from "./MorseReceiver.sol";
export type { morseReceiverSol };
import type * as morseSimpleSol from "./MorseSimple.sol";
export type { morseSimpleSol };
import type * as oneShotExploitSol from "./OneShotExploit.sol";
export type { oneShotExploitSol };
import type * as simpleContractSol from "./SimpleContract.sol";
export type { simpleContractSol };
export type { Target } from "./Target";
