/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVaultLib,
  IVaultLibInterface,
} from "../../../contracts/interfaces/IVaultLib";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "calcAssetAllocation",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "calcAssetForWithdrawals",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "verify",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVaultLib__factory {
  static readonly abi = _abi;
  static createInterface(): IVaultLibInterface {
    return new Interface(_abi) as IVaultLibInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVaultLib {
    return new Contract(address, _abi, runner) as unknown as IVaultLib;
  }
}
