/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IMorseInterface extends Interface {
  getFunction(nameOrSignature: "z1" | "z5"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "z1",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "z5", values?: undefined): string;

  decodeFunctionResult(functionFragment: "z1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "z5", data: BytesLike): Result;
}

export interface IMorse extends BaseContract {
  connect(runner?: ContractRunner | null): IMorse;
  waitForDeployment(): Promise<this>;

  interface: IMorseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  z1: TypedContractMethod<[x: BytesLike, y: AddressLike], [void], "nonpayable">;

  z5: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "z1"
  ): TypedContractMethod<[x: BytesLike, y: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "z5"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
