/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrancyGuard__factory>;
    getContractFactory(
      name: "GameMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.GameMaster__factory>;
    getContractFactory(
      name: "Bidding",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Bidding__factory>;
    getContractFactory(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRagnarokGameMaster__factory>;
    getContractFactory(
      name: "Descend",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Descend__factory>;
    getContractFactory(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRagnarokGameMaster__factory>;
    getContractFactory(
      name: "Doors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Doors__factory>;
    getContractFactory(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRagnarokGameMaster__factory>;
    getContractFactory(
      name: "Equilibrium",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Equilibrium__factory>;
    getContractFactory(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRagnarokGameMaster__factory>;
    getContractFactory(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRagnarokGameMaster__factory>;
    getContractFactory(
      name: "Threes",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Threes__factory>;
    getContractFactory(
      name: "IDoors",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IDoors__factory>;
    getContractFactory(
      name: "IGame",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IGame__factory>;
    getContractFactory(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IRagnarokGameMaster__factory>;

    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "ReentrancyGuard",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrancyGuard>;
    getContractAt(
      name: "GameMaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.GameMaster>;
    getContractAt(
      name: "Bidding",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Bidding>;
    getContractAt(
      name: "IRagnarokGameMaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRagnarokGameMaster>;
    getContractAt(
      name: "Descend",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Descend>;
    getContractAt(
      name: "IRagnarokGameMaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRagnarokGameMaster>;
    getContractAt(
      name: "Doors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Doors>;
    getContractAt(
      name: "IRagnarokGameMaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRagnarokGameMaster>;
    getContractAt(
      name: "Equilibrium",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Equilibrium>;
    getContractAt(
      name: "IRagnarokGameMaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRagnarokGameMaster>;
    getContractAt(
      name: "IRagnarokGameMaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRagnarokGameMaster>;
    getContractAt(
      name: "Threes",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Threes>;
    getContractAt(
      name: "IDoors",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IDoors>;
    getContractAt(
      name: "IGame",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IGame>;
    getContractAt(
      name: "IRagnarokGameMaster",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IRagnarokGameMaster>;

    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ReentrancyGuard",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "GameMaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GameMaster>;
    deployContract(
      name: "Bidding",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bidding>;
    deployContract(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "Descend",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Descend>;
    deployContract(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "Doors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Doors>;
    deployContract(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "Equilibrium",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Equilibrium>;
    deployContract(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "Threes",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Threes>;
    deployContract(
      name: "IDoors",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDoors>;
    deployContract(
      name: "IGame",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGame>;
    deployContract(
      name: "IRagnarokGameMaster",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;

    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "ReentrancyGuard",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrancyGuard>;
    deployContract(
      name: "GameMaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.GameMaster>;
    deployContract(
      name: "Bidding",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Bidding>;
    deployContract(
      name: "IRagnarokGameMaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "Descend",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Descend>;
    deployContract(
      name: "IRagnarokGameMaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "Doors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Doors>;
    deployContract(
      name: "IRagnarokGameMaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "Equilibrium",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Equilibrium>;
    deployContract(
      name: "IRagnarokGameMaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "IRagnarokGameMaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;
    deployContract(
      name: "Threes",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Threes>;
    deployContract(
      name: "IDoors",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IDoors>;
    deployContract(
      name: "IGame",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IGame>;
    deployContract(
      name: "IRagnarokGameMaster",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IRagnarokGameMaster>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
