/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMorse__factory } from "./IMorse__factory";
export { SimpleContract__factory } from "./SimpleContract__factory";
