/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../../common";
import type {
  SimpleContract,
  SimpleContractInterface,
} from "../../../../../contracts/hackathon/morse/SimpleContract.sol/SimpleContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "challenge",
        type: "address",
      },
    ],
    name: "exploit",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460135760dd908160198239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c630aeb4ddf14602857600080fd5b3460a357602036600319011260a357816004356001600160a01b0381169081900360a357803b1560a35760048383819363088fa68560e11b83525af180156098576070575080f35b67ffffffffffffffff811160845760405280f35b634e487b7160e01b82526041600452602482fd5b6040513d84823e3d90fd5b5080fdfea264697066735822122040fb621385c3b9f9f7ffa58ccff9d420e8cf10d4dab54b498128eace6d860e6b64736f6c634300081c0033";

type SimpleContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: SimpleContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class SimpleContract__factory extends ContractFactory {
  constructor(...args: SimpleContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      SimpleContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): SimpleContract__factory {
    return super.connect(runner) as SimpleContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): SimpleContractInterface {
    return new Interface(_abi) as SimpleContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SimpleContract {
    return new Contract(address, _abi, runner) as unknown as SimpleContract;
  }
}
